### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by brantje** [brantje/passman-chrome#1]
Browser extension:
- [ ] Auto fill when credential matches (domain/path or page) ->   When more available show a dropdown
- [ ] Ask to **save** password in Passman when a new password is detected (just like Chrome does)
  - [ ] Auto generate a new password
- [ ] Ask to **update** password in Passman when a new password is detected (just like Chrome does)
- [ ] When extension icon is clicked the 'main' page is opened, showing the current amount of credentials found for current (domain/path or page) 
- [ ] When a credential as a `otp` property, the extension should indicate that they can use the One time password generator from the extension. [OTP directive for angular js 1.*](https://github.com/nextcloud/passman/blob/master/js/app/directives/otp.js)
- [ ] A settings page to lock certain settings like URL of NextCloud envoirment password settings etc. 
- [ ] Strong encrypted communication in every way. 
- [ ] WebExtensions compatible API!

Suggestions? Add them! 
Once i'll add them to the list i delete the comment to keep this issue clean.

Example settings page
![image](https://cloud.githubusercontent.com/assets/2758767/21597738/e1d0fb16-d14f-11e6-95c6-e7c49e7c0d1f.png)

**Comment by enoch85** [comment]
- [ ] Ask to save password in Passman when a new password is detected (just like Chrome does)

**Comment by evaryont** [comment]
Since Firefox has some compatibility with Webextensions (to a degree, they are adding extra APIs as they run into issues current extensions have when migrating) will Firefox be a target browser, too?

And since I expect others may ask, what about Opera (and even Vivaldi?) support?

**Comment by maestroi** [comment]
@evaryont eventualy firefox will be supported yes, but we think its best to support most used browser at the start.

About Opera depens highly on demand. we have no expierience with extension creation so we just start easy.

**Comment by tapir** [comment]
Please please please consider WebExtensions compatible API only.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions
Since this is a really simple plugin, it should be quite OK I think.

**Comment by maestroi** [comment]
@tapir thank you for the suggestion! we will look into that!

**Comment by tapir** [comment]
@maestroi there are some small incompatiblities listed here: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities just FYI. The list is not long. With minimal care I believe your extension will work on all 4 big browsers. 💯 🥇

**Comment by maestroi** [comment]
@tapir thanks for the information!! i added them to the requirement list!

**Comment by brantje** [comment]
This issue was moved to nextcloud/passman-chrome-extension#1
